### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by devjeonghwan** [JisongXie/StegaStamp_pytorch#2]
I optimize train speed and training during 7 days on rtx 3090 gpu

but decoder does not working. secret loss not going down and accuray not going up.

did you test code?

**Comment by devjeonghwan** [comment]
and some layer(up sampling layers) not correctly converted. conv2d's padding not correct

**Comment by devjeonghwan** [comment]
Oops Sorry

**Comment by JisongXie** [comment]
Hi, @devjeonghwan, my code is not complete, maybe there are some bugs. The loss not going down and accuracy not going up means that training is wrong. I am so busy now that I have no much time to fix it. Maybe later I will review it.

**Comment by JisongXie** [comment]
Any contributions are welcome.
